---
- name: Symlink my dotfiles
  file: src=~/dotfiles/home/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .zshrc
    - .zshenv
    - .gitignore
    - .gitconfig
    - .tmux.conf
    - .config/nvim


- name: Clone tmux plugins
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm


- name: Install/update tmux plugins
  command: ~/.tmux/plugins/tpm/bin/update_plugins all

- name: Install/update VIM plugins
  command: vim +PluginInstall! +qall
