install ack
install bash
install curl
install fasd
install figlet
install git
install hub
install nmap
install node
install python
install python3
install readline
install rename
install ssh-copy-id
install toilet
install vim
install watch
install wget
install zsh

# casks
tap caskroom/cask
install brew-cask
cask install dropbox
cask install evernote
cask install google-chrome
cask install iterm2
cask install sublime-text
cask install hipchat
cask install viber
cask install github
cask install spotify
cask install macpass
cask install virtualbox
cask install trailer
cask install spotifree
cask install skitch
cask install flux
cask install tunnelblick
cask install sequel-pro
cask install vagrant
